### PR TITLE
Autoloading of projection classes

### PR DESCRIPTION
**Pull request by pjeweb**
Basically I got WGS84 -> EPSG:31467 (my use case) working by fixing the autoloading of projection classes (dc47e5d23a7d50493cbc33d52cf5e9f23165bb7b, 4a04a902c6308411b63a38a85c73e47e8773ac08).

If you don't agree on the code style changes (e5446670025171b0d61136fbd0bae99444612523) I would gladly make a pull request without them.

### CODE REVIEW

**Comment by judgej** [comment]
Code style changes are cool - I try to stick to PSR styling personally. Much of this code was a direct port from JavaScript, and some styling got carried across. I was concentrating mainly on functionality, and not gone back to fix styling yet.

**Comment by judgej** [comment]
Thanks.

**Comment by pjeweb** [comment]
Wow! Thanks for the very quick response ;)

**Comment by judgej** [comment]
Haven't tested your changes, but it all _looks_ good, so I just went for it :-)

**Pull request merged**
