### PR TITLE
necessary composer fields (and a little bit tuning)

### PR DESCRIPTION
**Pull request by chpio**

### CODE REVIEW

**Comment by judgej** [comment]
Can't say I fully understand the archive directive in composer.json, but let's go for it :-)

Thank you.

**Comment by chpio** [comment]
Am 26.02.2015 um 22:26 schrieb Jason Judge:

> Can't say I fully understand the archive directive in composer.json, but let's go for it :-)

that's used when you make an archive out of the module eg. with
[satis](https://github.com/composer/satis). So, the directive tells the
archiver to ignore some files, in this case everything beside the src
directory.

**Comment by judgej** [comment]
So it helps when building private composer repositories (as an alternative to packagist, but shareable within, say, an organisation)?

**Comment by chpio** [comment]
yeah, it helps to reduce the installation size by keeping unneeded files out. (in case you need them, you can install the package from the sources `--prefer-source`).

i just don't know where the archiver is used (besides by satis)

**Comment by judgej** [comment]
Cool, thanks for explaining.

**Comment by chpio** [comment]
hmm, there is a bug in composer... https://github.com/composer/composer/issues/3796
and it causes to brake this package if installed as archive. 
my workaround was to also include the _composer.json_ file.

``` json
...

                        "archive": {
                            "exclude": [
                                "*",
                                ".*",
                                "!/src/*",
                                "!/composer.json"
                            ]
                        },

...
```

**Pull request merged**
